### ISSUE TITLE
[REQ] Show default CS2 skins in inventory for new players

### ISSUE THREAD

**Issue by crashzk** [L1teD/cs2-WeaponPaints-website#2]
I noticed that even though I didn't select any skin in the web interface, when I logged in it automatically showed the weapons with skins, as if I had chosen them.
<img width="696" alt="image" src="https://github.com/L1teD/cs2-WeaponPaints-website/assets/32937653/cb5e2bb8-4b2f-4122-a83e-544fefe9be4e">

Isos in the case for all weapons, only the knives that are not in the case. Wouldn't it be more interesting to show the default CS2 skins if the player hasn't chosen any yet? Would that be possible?

**Comment by L1teD** [comment]
Yes, that's possible
It's because API that I'm using for skins have defaults only for knives, when i finish my own json for defaults it will look right
