### ISSUE TITLE
[HELP] Installing on web hosting

### ISSUE THREAD

**Issue by RodyaUshakov** [L1teD/cs2-WeaponPaints-website#21]
Hello, how do I install on web hosting? Can I have more details, please?

**Comment by L1teD** [comment]
Hi, first of all you need a VPS with NodeJS and Nginx installed on it
Then make a reverse proxy on `http://localhost:{PORT}` (you can find plenty of tutorials)

Pretty easy to install, but if you will have some issues with this, feel free to DM me in Discord (l1tedxd)
