### ISSUE TITLE
Does the PRVIATE version support image cache?

### ISSUE THREAD

**Issue by shoval-dev** [L1teD/cs2-WeaponPaints-website#25]
I'm in China and currently the website is slow to access the content on github, so I'd like to ask if the PRVIATE version can cache images from github to a local server.

**Comment by L1teD** [comment]
Will do

**Comment by NoSetViolin** [comment]
need latest image cache! i cant find it. in china it can not load the skin images

**Comment by L1teD** [comment]
Added into rewrited version,
wait for release
And don't close the issue please

**Comment by NoSetViolin** [comment]
i just got it
Download [counter-strike-image-tracker](https://github.com/ByMykel/counter-strike-image-tracker/)
unzip static/panorama/images   to   web/public/image   
change  raw.github url  to  local url   in web/public/js/json/skins
如果你是中国人，并且想询问更多可以加我qq

**Comment by NoSetViolin** [comment]
i just got it
Download [counter-strike-image-tracker](https://github.com/ByMykel/counter-strike-image-tracker/)
unzip static/panorama/images to web/public/image
change raw.github url to local url in web/public/js/json/skins/zh-CN-skins.json
如果你是中国人，并且想询问更多可以加我qq

**Comment by shoval-dev** [comment]
> i just got it Download [counter-strike-image-tracker](https://github.com/ByMykel/counter-strike-image-tracker/) unzip static/panorama/images to web/public/image change raw.github url to local url in web/public/js/json/skins/zh-CN-skins.json 如果你是中国人，并且想询问更多可以加我qq

你的QQ是什么

**Comment by NoSetViolin** [comment]
> > i just got it Download [counter-strike-image-tracker](https://github.com/ByMykel/counter-strike-image-tracker/) unzip static/panorama/images to web/public/image change raw.github url to local url in web/public/js/json/skins/zh-CN-skins.json 如果你是中国人，并且想询问更多可以加我qq
> 
> 你的QQ是什么

452861927
