### ISSUE TITLE
Is it possible to somehow launch a website via xampp and if so, how?

### ISSUE THREAD

**Issue by this-is-really** [L1teD/cs2-WeaponPaints-website#28]
I don’t know how to create websites, I don’t know how to unpack them. Can you help me set up a website using xampp or recommend some other application?
I used a translator, so some points may not be entirely clear.

**Comment by L1teD** [comment]
First of all, to run this website you need Node.JS
Apache (xampp), will act as reverse proxy (domain.com -> http://localhost:27275)
But i would heavily recommend to use nginx instead of apache
