### ISSUE TITLE
Still getting STATUS_BREAKPOINT

### ISSUE THREAD

**Issue by kaan1705** [L1teD/cs2-WeaponPaints-website#29]
Hey i'm still getting the status_breakpoint error despite updating to the latest version that was released 5 days ago. Its only happening in chrome based browsers such as brave tho. Works totally fine with Firefox. I have tried clearing cache and accessing the site through incognito mode but with no luck. Is this a known issue or is it something wrong with my setup? Running Nginx with php 8.2, node 20.15.0, npm 10.7.0 and nginx proxy manager

**Comment by L1teD** [comment]
Hi, right now i see that app is disabled (Error 502)
Other webs that are running 2.0.12 is not getting this issue, so it might be issue with caching somewhere (e.g. CloudFlare)
Can you run app so i can look what's wrong?

**Comment by kaan1705** [comment]
I never even considered that cloudflare was caching. That was the issue. Thank you!
