### ISSUE TITLE
Steam Login Failing Consistently

### ISSUE THREAD

**Issue by leodenglovescode** [L1teD/cs2-WeaponPaints-website#30]
Hello! I am a cs2 server owner, and by installing the skinchanger from Nereziels' github repo, I came across this website which seems usable unlike the original one, however, I ran in to the exact same problem on this website, that is, when I press the steam login button, nothing happens, then an error pops up on the console telling me there was a "Internal OpenID Error", which renders the website completely useless because nobody can change the skins from the console. I also did not forget to fill in any information such as the SteamAPI Key and the database information, so any help would be greatly appreciated (Some Screenshots of the Error is down below)!

System (Server):
ThinkPad E450 
8GB RAM
Windows 10

Release of this website: v2.0.13_3.5.9

![Screenshot 2024-10-20 235554](https://github.com/user-attachments/assets/1eb33f82-f1fd-4258-a1dc-4c944201b0ed)
![Screenshot 2024-10-20 235619](https://github.com/user-attachments/assets/54f44ffb-82d3-4dc8-a8e8-107a640377e0)

**Comment by L1teD** [comment]
Main reason why this happens is steam api is unavailable at the moment, probably will fix itself after time but if no, contact me on discord: l1tedxd

**Comment by leodenglovescode** [comment]
Closing issue as time problem

**Comment by leodenglovescode** [comment]
FIXED ISSUE USING PROXY (FOR USERS IN CHINA):
Parameters: npm --proxy http://proxy adress: proxy port run dev
