### ISSUE TITLE
something about keychain and stickers

### ISSUE THREAD

**Issue by NoSetViolin** [L1teD/cs2-WeaponPaints-website#34]
Bro, I saw you just replied to me in the weaponpaints project. I would like to know whether weaponpaints supports keychain and stickers changes. And I see the comment in the database, but I don't know how to modify it to make it available.

**Comment by L1teD** [comment]
Yes it's supports stickers and keychains
First of all, check if you downloaded all needed dependencies for plugin
For getting x, y values use cs2inspects website for now (all stickers using x, y values from first sticker slot)
Private version of my website will also support stickers and keychains, and it'll be available in around 1.5-2 weeks
